"*": sRGB
Face_ChannelPack: Non-Color
Arms_ChannelPack: Non-Color
Legs_ChannelPack: Non-Color
Torso_ChannelPack: Non-Color
Iris_Height_Edit: Non-Color
ReomLipMask: Non-Color
EyeSclera_Cornea_Opacity: Non-Color
EyeSclera_Height: Non-Color
